services:
  db:
    image: mysql:8.0
    container_name: ads_aggregator_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ads_aggregator_network

volumes:
  db_data:

networks:
  ads_aggregator_network:
    driver: bridge