services:
  nginx:
    image: nginx:alpine
    container_name: ads_aggregator_nginx_prod
    ports:
      - "80:80"
    volumes:
      - app_data:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: muhammadhakim33/ads-aggregator-app:latest
    container_name: ads_aggregator_app_prod
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    volumes:
      # Kontainer app akan mengisi named volume ini dengan file source code-nya
      - app_data:/var/www/html

  db:
    image: mysql:8.0
    container_name: ads_aggregator_db_prod
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_data:
