server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    # remove index.php from url (CI3 URL routing)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        # pass CI_ENV to PHP
        fastcgi_param CI_ENV development;
    }

    # block access to sensitive folder CI3
    location ~ ^/(application|system)/ {
        deny all;
    }
}