<?php
defined('BASEPATH') or exit('No direct script access allowed');

$config['platforms'] = [
    'facebook' => [
        'enabled' => true,
        'label' => 'Facebook',
        'driver_class' => 'FacebookDriver',
        'driver_path' => APPPATH . 'modules/facebook/FacebookDriver.php',
        'metrics' => [
            "post_engagements",
            "post_engagement_rate",
            "post_reactions_like_total",
            "post_reactions_love_total",
            "post_reactions_wow_total",
            "post_reactions_haha_total",
            "post_reactions_sorry_total",
            "post_reactions_anger_total",
            "post_comments",
            "post_shares",
            "post_clicks",
            "post_clicks_by_type",
            "post_impressions",
            "post_impressions_organic",
            "post_impressions_paid",
            "post_impressions_viral",
            "post_reach",
            "post_reach_organic",
            "post_reach_paid",
            "post_reach_viral",
            "post_impressions_by_age_gender",
            "post_impressions_by_city",
            "post_impressions_by_country",
            "post_impressions_organic_by_age_gender",
            "post_impressions_organic_by_city",
            "post_impressions_organic_by_country"
        ],
        'filters' => [
            'keyword' => true,
            'hostname' => false,
            'html' => false,
        ],
    ],
    'instagram' => [
        'enabled' => true,
        'label' => 'Instagram',
        'driver_class' => 'InstagramDriver',
        'driver_path' => APPPATH . 'modules/instagram/InstagramDriver.php',
        'metrics' => [
            "total_like_count",
            "total_comments_count",
            "total_views_count",
            "total_likes",
            "total_comments",
            "total_views",
            "view_count",
            "reposts_count",
            "saved_count",
            "shares_count",
            "reels_skip_rate",
            "crossposted_views",
            "facebook_views",
            "profile_activity",
            "impressions",
            "reach",
            "exits",
            "content_monetization_earnings"
        ],
        'reels_metrics' => [
            'ig_reels_avg_watch_time',
            'ig_reels_video_view_total_time',
            'reels_skip_rate',
        ],
        'filters' => [
            'keyword' => true,
            'hostname' => false,
            'html' => false,
        ],
    ],
    'youtube' => [
        'enabled' => true,
        'label' => 'YouTube',
        'driver_class' => 'YoutubeDriver',
        'driver_path' => APPPATH . 'modules/youtube/YoutubeDriver.php',
        'metrics' => [
            'viewCount',
            'likeCount',
            'commentCount',
        ],
        'filters' => [
            'keyword' => true,
            'hostname' => false,
            'html' => false,
        ],
    ],
    'ga4' => [
        'enabled' => true,
        'label' => 'Google Analytics 4',
        'driver_class' => 'Ga4Driver',
        'driver_path' => APPPATH . 'modules/ga4/Ga4Driver.php',
        'filters' => [
            'keyword' => false,
            'hostname' => true,
            'html' => true,
        ],
        'metrics' => [
            "totalUsers",
            "activeUsers",
            "newUsers",
            "dauPerMau",
            "sessions",
            "engagedSessions",
            "engagementRate",
            "averageSessionDuration",
            "sessionsPerUser",
            "engagedSessionsPerUser",
            "eventCount",
            "eventCountPerUser",
            "eventValue",
            "eventValuePerEvent",
            "eventConversionRate",
            "screenPageViews",
            "screenPageViewsPerSession",
            "screenPageViewsPerUser",
            "userEngagementDuration",
            "averageEngagementTimePerSession",
            "averageEngagementTimePerUser",
            "bounceRate",
            "keyEvents",
            "keyEventConversionRate",
            "sessionKeyEventRate",
            "totalRevenue",
            "revenuePerUser",
            "revenuePerSession",
            "itemsViewed",
            "itemsAdded",
            "itemsCheckedOut",
            "itemsPurchased",
            "itemsRefunded",
            "cartAbandonmentRate",
            "purchasesToViewsRate",
            "itemsRefundedRate",
            "adUnitExposures",
            "impressions",
            "clicks",
            "cost",
            "costPerClick",
            "costPerConversion",
            "ctr",
            "roas",
            "conversions",
            "conversionRate",
            "conversionValue",
            "videoViews",
            "videoEngagedViews",
            "videoPerspectiveRate",
            "videoAvgViewDuration",
            "videoAvgEngagedViewDuration",
            "cohortActiveUsers",
            "cohortTotalUsers",
            "cohortRetentionRate",
            "cohortUsersWithEngagedSession",
            "returnedUsers",
            "userRetentionRate",
            "userSessionsPerUserSegment",
            "userDaysLastSeen",
            "userFirstSessionDate",
            "percentScrolled",
            "totalPublisherRevenue",
            "activeProductListUsers",
            "activeProductDetailUsers",
            "activeCheckoutUsers"
        ],
    ],
];