<?php
defined('BASEPATH') or exit('No direct script access allowed');

$config['platforms'] = [
    'facebook' => [
        'enabled' => true,
        'label' => 'Facebook',
        'driver_class' => 'FacebookDriver',
        'driver_path' => APPPATH . 'modules/facebook/FacebookDriver.php',
        'metrics' => [
            "post_engaged_users",
            "post_impressions",
            "post_impressions_unique",
            "post_impressions_paid",
            "post_impressions_paid_unique",
            "post_impressions_organic",
            "post_impressions_organic_unique",
            "post_impressions_viral",
            "post_impressions_viral_unique",
            "post_clicks",
            "post_clicks_by_type",
            "post_reactions_like_total",
            "post_reactions_love_total",
            "post_reactions_wow_total",
            "post_reactions_haha_total",
            "post_reactions_sorry_total",
            "post_reactions_anger_total",
            "post_reactions_by_type_total",
            "post_media_view",
            "post_total_media_view_unique"
        ],
        'filters' => [
            'keyword' => true,
            'hostname' => false,
            'html' => false,
        ],
    ],
    'instagram' => [
        'enabled' => true,
        'label' => 'Instagram',
        'driver_class' => 'InstagramDriver',
        'driver_path' => APPPATH . 'modules/instagram/InstagramDriver.php',
        'metrics' => [
            "likes",
            "comments",
            "views",
            "saved",
            "shares",
            "reposts",
            "total_interactions",
            "profile_activity",
            "profile_visits",
            "impressions",
            "reach",
            "follows",
            "facebook_views"
        ],
        'reels_metrics' => [
            'ig_reels_avg_watch_time',
            'ig_reels_video_view_total_time',
            'reels_skip_rate',
            'crossposted_views'
        ],
        'filters' => [
            'keyword' => true,
            'hostname' => false,
            'html' => false,
        ],
    ],
    'youtube' => [
        'enabled' => true,
        'label' => 'YouTube',
        'driver_class' => 'YoutubeDriver',
        'driver_path' => APPPATH . 'modules/youtube/YoutubeDriver.php',
        'metrics' => [
            // YouTube Data API metrics
            'viewCount',
            'likeCount',
            'commentCount',
            
            // YouTube Analytics API metrics
            'views',
            'estimatedMinutesWatched',
            'averageViewDuration',
            'averageViewPercentage',
            'audienceWatchRatio',
            'viewerPercentage',
            'engagedViews',
            'likes',
            'dislikes',
            'comments',
            'shares',
            'subscribersGained',
            'subscribersLost',
            'estimatedRevenue',
            'estimatedAdRevenue',
            'grossRevenue',
            'cpm',
            'playbackBasedCpm',
            'adImpressions',
            'monetizedPlaybacks',
            'cardImpressions',
            'cardClicks',
            'cardClickRate',
            'cardTeaserImpressions',
            'cardTeaserClicks',
            'cardTeaserClickRate',
            'videoThumbnailImpressions',
            'videoThumbnailImpressionsClickRate',
            'playlistStarts',
            'playlistViews',
            'playlistEstimatedMinutesWatched',
            'viewsPerPlaylistStart',
            'videosAddedToPlaylists',
            'videosRemovedFromPlaylists'
        ],
        'filters' => [
            'keyword' => true,
            'hostname' => false,
            'html' => false,
        ],
    ],
    'ga4' => [
        'enabled' => true,
        'label' => 'Google Analytics 4',
        'driver_class' => 'Ga4Driver',
        'driver_path' => APPPATH . 'modules/ga4/Ga4Driver.php',
        'filters' => [
            'keyword' => false,
            'hostname' => true,
            'html' => true,
        ],
        'metrics' => [
            "totalUsers",
            "activeUsers",
            "newUsers",
            "dauPerMau",
            "sessions",
            "engagedSessions",
            "engagementRate",
            "averageSessionDuration",
            "sessionsPerUser",
            "engagedSessionsPerUser",
            "eventCount",
            "eventCountPerUser",
            "eventValue",
            "eventValuePerEvent",
            "eventConversionRate",
            "screenPageViews",
            "screenPageViewsPerSession",
            "screenPageViewsPerUser",
            "userEngagementDuration",
            "averageEngagementTimePerSession",
            "averageEngagementTimePerUser",
            "bounceRate",
            "keyEvents",
            "keyEventConversionRate",
            "sessionKeyEventRate",
            "totalRevenue",
            "revenuePerUser",
            "revenuePerSession",
            "itemsViewed",
            "itemsAdded",
            "itemsCheckedOut",
            "itemsPurchased",
            "itemsRefunded",
            "cartAbandonmentRate",
            "purchasesToViewsRate",
            "itemsRefundedRate",
            "adUnitExposures",
            "impressions",
            "clicks",
            "cost",
            "costPerClick",
            "costPerConversion",
            "ctr",
            "roas",
            "conversions",
            "conversionRate",
            "conversionValue",
            "videoViews",
            "videoEngagedViews",
            "videoPerspectiveRate",
            "videoAvgViewDuration",
            "videoAvgEngagedViewDuration",
            "cohortActiveUsers",
            "cohortTotalUsers",
            "cohortRetentionRate",
            "cohortUsersWithEngagedSession",
            "returnedUsers",
            "userRetentionRate",
            "userSessionsPerUserSegment",
            "userDaysLastSeen",
            "userFirstSessionDate",
            "percentScrolled",
            "totalPublisherRevenue",
            "activeProductListUsers",
            "activeProductDetailUsers",
            "activeCheckoutUsers"
        ],
    ],
];